blockExoticSubdeps: true
autoInstallPeers: false
minimumReleaseAge: 2880
trustPolicy: no-downgrade
strictPeerDependencies: true
strictDepBuilds: true

color: always

packages:
   - "packages/*"

trustPolicyExclude:
   - "semver@6.3.1"

onlyBuiltDependencies:
   - simple-git-hooks
