saveExact: true
blockExoticSubdeps: true
autoInstallPeers: false
minimumReleaseAge: 2880
trustPolicy: no-downgrade
strictPeerDependencies: true
strictDepBuilds: true
dedupePeers: true
shellEmulator: true

color: always

packages:
   - "packages/*"

trustPolicyExclude:
   - "semver@6.3.1"

allowBuilds:
   simple-git-hooks: true
